# json과 비슷하지만, kubernetes같은 자동화 및 배포에 많이 사용됨

version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     volumes: 
        - ./wp-content:/var/www/html/wp-content
volumes:
    db_data: {}
    # db_data를 모든 서비스에서 사용 가능

    # wordpress - docker hub
   # 테마는 다음의 하위 디렉토리에 있습니다. /var/www/html/wp-content/themes/
   #플러그인은 /var/www/html/wp-content/plugins/


# % docker-compose up -d  
# -d : 터미널에서 분리되었기 떄문에 없으면 모든 process run / background task, able to use terminal